const express = require("express")
const router = express.Router()
const sample_controller = require("../controllers/sample_controller")
const passport = require("../config/passport-local-strategy")
const upload = require("../config/multer")

router.post("/scheduleasample",passport.isAuth,sample_controller.scheduleASample)
router.post("/samplingsurvey/:id",passport.isAuth,upload.fields([{name: "sample_image",maxCount: 1},{name: "location_image",maxCount: 1}]),sample_controller.samplingSurvey)
router.get("/getallsamples",passport.isAuth,sample_controller.getAllSamples)
router.post("/changeapprovalstatus/:id",passport.isFSO,sample_controller.changeApprovleStatus)
router.get("/getsamplecity",passport.isAuth,sample_controller.getSampleFromCity)
router.get("/getsamplefso",passport.isAuth,sample_controller.getSampleFso)
router.post("/aftersignature/:id",passport.isAuth,upload.fields([{name:"fso_signature_image",maxCount:1},{name:"si_signature_image",maxCount:1}]),sample_controller.afterSignature)
router.get("/dataforpdf/:id",passport.isAuth,sample_controller.dataForPdf)
module.exports = router